---
- name: remove mymaster config from sentinel
  lineinfile:
    dest: /etc/redis-sentinel.conf
    regexp: 'sentinel.*mymaster'
    state: absent

- name: set redis sentinel config
  template:
    src: redis-sentinel.conf
    dest: /etc/redis-sentinel.conf
  notify:
    - restart redis sentinel

- name: start redis sentinel
  service:
    name: redis-sentinel
    state: started
    enabled: yes
...
