---
- name: install redis server
  package:
    name: redis-3.2.8
    state: present
    enablerepo: remi

- name: bind redis to all ip addresses
  lineinfile:
    dest: /etc/redis.conf
    regexp: '(# *)?bind'
    state: absent
  notify: restart redis server

- name: set redis server password
  lineinfile:
    dest: /etc/redis.conf
    regexp: '(# *)?requirepass'
    line: 'requirepass foobared'
  notify: restart redis server

- name: insert slave config
  lineinfile:
    dest: /etc/redis.conf
    regexp: '^slaveof '
    line: "slaveof {{ hostvars['redis1']['ansible_eth1']['ipv4']['address'] }} 6379"
  when: "hostvars['redis1']['ansible_eth1']['ipv4']['address'] != hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']"
  notify:
    - restart redis server

- name: insert slave config
  lineinfile:
    dest: /etc/redis.conf
    regexp: '^masterauth '
    line: 'masterauth foobared'
  when: "hostvars['redis1']['ansible_eth1']['ipv4']['address'] != hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']"

- name: start redis server
  service:
    name: redis
    state: started
    enabled: yes
...
